---
- hosts: webservers
  become: true 
  become_user: sudo

  tasks:
    - name: Installation des paquets communs à tous les serveurs
      apt:
        update_cache: yes
        state: latest
        name: ['glances', 'pwgen', 'sudo', 'tar', 'unzip', 'vim', 'whois']
