---
# tasks file for common
#
# Mise à jour du système d'exploitation
- name: Check server up to date
  apt:
    update_cache: yes
    upgrade: dist
# Installation des paquets communs à installer pour les taĉhes d'administration:    
  name:
      - fail2ban
      - htop
      - vim
      - man
      - manpages-fr
      - bash-completion
      - wget
      - zip
      - curl
      - sudo
      - pwgen


